[package]
name = "fuzzer_compare"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
once_cell = "1.18.0"


[profile.release]
panic = 'abort'
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
