---
required: ["init_lib", "data_lib", "db", "passwd", "user_name", "host", "db_name", "startup_cmd"]
should_exist: ["init_lib", "data_lib"]
init_lib: /home/lcf/shuimu-dev/fuzzer-compare/fuzzers/squirrel/data/fuzz_root/pqsql_init_lib
data_lib: /home/lcf/shuimu-dev/fuzzer-compare/fuzzers/squirrel/data/fuzz_root/global_data_lib_pqsql
data_lib: 
db: postgresql
passwd: '1234'
user_name: postgres
db_name: postgres
host: localhost
port: 5432
startup_cmd: "$PGSQL_INSTALL_PATH/bin/postgres -D $TEST_PATH/data &"
