---
required: ["init_lib", "data_lib", "db", "passwd", "user_name", "host", "sock_path", "db_prefix", "startup_cmd"]
should_exist: ["init_lib", "data_lib"]
init_lib: /home/lcf/shuimu-dev/fuzzer-compare/fuzzers/squirrel/data/fuzz_root/mysql_init_lib
data_lib: /home/lcf/shuimu-dev/fuzzer-compare/fuzzers/squirrel/data/fuzz_root/global_data_lib_mysql
db: mysql
passwd: ''
user_name: root
host: localhost
sock_path: "/tmp/another_mysql.sock"
db_prefix: test
startup_cmd: "$MYSQL_INSTALL_PATH/bin/mysqld --port=3307 --basedir=$MYSQL_INSTALL_PATH --datadir=$TEST_PATH/data &"